name: CI

on:
  # push:
  #   branches:
  #     - '*'
  #     - '!main'  # Exclude 'main' branch
  pull_request:
    branches:
      - 'main'


jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          node-version: '20'

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # - uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'

      - name: Install Dependencies
        run: npm install

      - run: npm install -g firebase-tools
      - run: npm ci

      - name: Run Firebase Emulator and perform tests
        run: npm run test-gh-action

      # - name: Run Tests
      #   run: npm test-gh-action
      #   id: test-result

      - name: Throw Error on Test Failure
        run: |
          if [ ${{ steps.test-result.outcome }} == 'failure' ]; then
            echo "Error: Tests failed. Exiting test execution."
            exit 1
          fi

      - name: Prevent Merge on Test Failure
        run: |
          echo "Error: Tests failed. Merging to main is not allowed."
          exit 1
        if: github.event_name == 'pull_request' && failure()

  failure:
    runs-on: ubuntu-latest
    environment: test-environment
    steps:
      - name: Check for Failed Tests
        run: exit 0  # This step always succeeds; it's used to trigger the 'failure' job